function renderCreateQuestion() {
  shell(`<section class="panel form-panel"><h1 class="section-title">나만의 문제 만들기</h1><p class="small-title">직무 지식을 문제로 정리하고, 다음 퀴즈에서 다시 풀어보세요.</p><form onsubmit="handleQuestionCreate(event)"><div class="form-grid"><div class="form-group"><label>분야</label><select name="domain" required onchange="updateCategoryOptions(this.value)"><option value="display">디스플레이</option><option value="semiconductor">반도체</option></select></div><div class="form-group"><label>직무 카테고리</label><select name="category" required>${categoryOptions()}</select></div><div class="form-group"><label>난이도</label><select name="difficulty"><option>입문</option><option>기초</option><option>중급</option><option>고급</option></select></div></div><div class="form-group"><label>문제</label><textarea name="question" required maxlength="300" placeholder="예: OLED 봉지 공정의 목적은 무엇인가요?"></textarea></div><div class="form-grid option-grid">${[0,1,2,3].map(i => `<div class="form-group"><label>보기 ${String.fromCharCode(65+i)}</label><input name="option${i}" required maxlength="100" /></div>`).join('')}</div><div class="form-group"><label>정답</label><select name="answer"><option value="0">보기 A</option><option value="1">보기 B</option><option value="2">보기 C</option><option value="3">보기 D</option></select></div><div class="form-group"><label>해설</label><textarea name="explanation" required maxlength="500" placeholder="정답인 이유와 면접에서 설명할 핵심을 적어주세요."></textarea></div><div class="row"><button class="primary-btn" type="submit">문제 저장</button><button class="ghost-btn" type="button" onclick="go('mypage')">취소</button></div></form></section>`, 'create');
}
function categoryOptions() { return Object.entries(DATA.display.categories).map(([key, category]) => `<option value="${key}">${category.label}</option>`).join(''); }
function updateCategoryOptions(domain) { const select = document.querySelector('select[name="category"]'); if (select) select.innerHTML = Object.entries(DATA[domain].categories).map(([key, category]) => `<option value="${key}">${category.label}</option>`).join(''); }
function handleQuestionCreate(event) {
  event.preventDefault();
  const form = new FormData(event.target); const user = getUser();
  const question = { id: Date.now(), domain: form.get('domain'), category: form.get('category'), difficulty: form.get('difficulty'), q: form.get('question'), options: [0,1,2,3].map(i => form.get(`option${i}`)), answer: Number(form.get('answer')), explanation: form.get('explanation'), author: user.name };
  saveCustomQuestions([question, ...getCustomQuestions()]);
  alert('문제가 저장되었습니다. 해당 카테고리 퀴즈에서 출제됩니다.'); goDomain(question.domain);
}

function renderCommunity(room = 'all', topic = 'all') {
  // 게시글과 댓글을 같은 배열로 관리해 새로고침 후에도 유지합니다.
  const topics = { all: '전체', jobs: '취업 정보', resume: '자소서·면접', role: '직무 이야기', study: '학습 질문' };
  const topicEntries = room === 'job' ? Object.entries(topics).filter(([key]) => key !== 'study') : Object.entries(topics);
  const posts = getPosts().filter(post => (room === 'all' || (post.room || 'all') === room) && (topic === 'all' || (post.category || 'role') === topic));
  const roomTitle = room === 'study' ? '학습방' : room === 'job' ? '취업 정보 공유방' : '커뮤니티';
  const roomDescription = room === 'job' ? '채용 소식과 취업 준비 정보를 공유해보세요.' : '관심사와 경험을 자유롭게 나누는 게시판입니다.';
  const cards = posts.length ? posts.map(post => `<article class="community-post"><div class="post-meta"><div class="post-badges"><span class="badge">${escapeHtml(post.category ? topics[post.category] : post.domain)}</span>${post.category ? `<span class="topic-badge">${escapeHtml(post.domain)}</span>` : ''}</div><span>${escapeHtml(post.author)} · ${escapeHtml(post.date)}</span></div><h3>${escapeHtml(post.title)}</h3><p>${escapeHtml(post.body)}</p><div class="post-footer"><span>💬 ${post.comments.length}개 댓글</span><button class="link-btn" onclick="toggleComments(${post.id})">댓글 보기/쓰기</button></div><div id="comments-${post.id}" class="comments" hidden>${post.comments.map(comment => `<p><strong>${escapeHtml(comment.author)}</strong> ${escapeHtml(comment.body)}</p>`).join('') || '<p class="empty">첫 번째 댓글을 남겨보세요.</p>'}<form onsubmit="handleComment(event, ${post.id})"><input name="body" required maxlength="200" placeholder="답변이나 지식을 공유해보세요" /><button class="primary-btn" type="submit">등록</button></form></div></article>`).join('') : '<div class="empty">아직 게시글이 없습니다. 첫 지식을 공유해보세요.</div>';
  const topicFilters = topicEntries.map(([key, label]) => `<button class="community-filter ${topic === key ? 'active' : ''}" onclick="renderCommunity('${room}', '${key}')">${label}</button>`).join('');
  shell(`<div class="grid two-col community-layout"><section><div class="community-heading"><div><h1 class="section-title">${roomTitle}</h1><p class="small-title">${roomDescription}</p></div><button class="primary-btn" onclick="requireLogin(()=>renderPostForm('${room}'))">글쓰기</button></div><div class="community-topics" role="tablist" aria-label="커뮤니티 주제">${topicFilters}</div><div class="community-list">${cards}</div></section><aside class="panel community-guide"><h2 class="section-title">${room === 'job' ? '취업 정보 가이드' : '자유 게시판 안내'}</h2><div class="community-guide-list"><div><strong>취업 정보</strong><span>채용 일정과 준비 전략</span></div><div><strong>자소서·면접</strong><span>합격 사례와 답변 피드백</span></div><div><strong>직무 이야기</strong><span>현업 용어와 직무 경험</span></div>${room === 'job' ? '' : '<div><strong>학습 질문</strong><span>퀴즈와 공부 방법</span></div>'}</div><p>서로의 경험을 존중하며 구체적인 정보와 근거를 함께 공유해보세요.</p></aside></div>`, room === 'all' ? 'community' : 'job-room');
}
function renderPostForm(room = 'all') { const title = room === 'job' ? '취업 정보 공유방 글쓰기' : '커뮤니티 글쓰기'; const categoryOptionsHtml = (room === 'job' ? [['jobs', '취업 정보'], ['resume', '자소서·면접'], ['role', '직무 이야기']] : [['jobs', '취업 정보'], ['resume', '자소서·면접'], ['role', '직무 이야기'], ['study', '학습 질문']]).map(([value, label]) => `<option value="${value}">${label}</option>`).join(''); shell(`<section class="panel form-panel"><h1 class="section-title">${title}</h1><form onsubmit="handlePostCreate(event, '${room}')"><div class="form-grid"><div class="form-group"><label>주제</label><select name="category">${categoryOptionsHtml}</select></div><div class="form-group"><label>분야</label><select name="domain"><option>디스플레이</option><option>반도체</option><option>취업 일반</option></select></div><div class="form-group"><label>제목</label><input name="title" required maxlength="80" placeholder="공유하고 싶은 내용을 한 줄로 적어주세요" /></div></div><div class="form-group"><label>내용</label><textarea name="body" required maxlength="1000" placeholder="답변, 지식, 정보 또는 질문을 작성해주세요."></textarea></div><div class="row"><button class="primary-btn" type="submit">게시하기</button><button class="ghost-btn" type="button" onclick="go('${room === 'job' ? 'job-room' : 'community'}')">취소</button></div></form></section>`, room === 'job' ? 'job-room' : 'community'); }
function handlePostCreate(event, room = 'all') { event.preventDefault(); const form = new FormData(event.target); const user = getUser(); savePosts([{ id: Date.now(), room, category: form.get('category'), domain: form.get('domain'), title: form.get('title'), body: form.get('body'), author: user.name, date: new Date().toLocaleDateString('ko-KR'), comments: [] }, ...getPosts()]); go(room === 'all' ? 'community' : room === 'study' ? 'study-room' : 'job-room'); }
function toggleComments(id) { const comments = document.querySelector(`#comments-${id}`); if (comments) comments.hidden = !comments.hidden; }
function handleComment(event, postId) { event.preventDefault(); const form = new FormData(event.target); const posts = getPosts(); const post = posts.find(item => item.id === postId); if (!post) return; post.comments.push({ author: getUser().name, body: form.get('body') }); savePosts(posts); renderCommunity(post.room || 'all'); }

function renderStudyRoom(domainFilter = 'all', categoryFilter = 'all') {
  const pool = [...QUESTIONS, ...getCustomQuestions()];
  const domains = [['all', '전체'], ...Object.entries(DATA).map(([key, data]) => [key, data.label])];
  const questions = pool.filter(question => (domainFilter === 'all' || question.domain === domainFilter) && (categoryFilter === 'all' || question.category === categoryFilter));
  const categoryEntries = domainFilter === 'all' ? [] : Object.entries(DATA[domainFilter].categories);
  const domainFilters = domains.map(([key, label]) => `<button class="community-filter ${domainFilter === key ? 'active' : ''}" onclick="renderStudyRoom('${key}', 'all')">${label}</button>`).join('');
  const categoryFilters = categoryEntries.length ? `<div class="study-category-filters"><button class="community-filter ${categoryFilter === 'all' ? 'active' : ''}" onclick="renderStudyRoom('${domainFilter}', 'all')">전체 직무</button>${categoryEntries.map(([key, category]) => `<button class="community-filter ${categoryFilter === key ? 'active' : ''}" onclick="renderStudyRoom('${domainFilter}', '${key}')">${category.label}</button>`).join('')}</div>` : '';
  const cards = questions.length ? questions.map(question => `<article class="study-card"><div class="post-meta"><span class="badge">${DATA[question.domain].label}</span><span>${DATA[question.domain].categories[question.category].label} · ${escapeHtml(question.difficulty)}</span></div><h3>${escapeHtml(question.q)}</h3><p>${escapeHtml(question.explanation)}</p><button class="ghost-btn" onclick="startQuiz('${question.domain}', '${question.category}', 'normal', false)">이 직무 퀴즈 풀기</button></article>`).join('') : '<div class="empty">해당 분야와 직무의 학습 내용이 없습니다.</div>';
  shell(`<section class="panel study-room-header"><h1 class="section-title">학습방</h1><p class="small-title">퀴즈에 나온 핵심 내용을 분야와 직무별로 찾아보세요.</p><div class="community-topics" role="tablist" aria-label="학습 분야">${domainFilters}</div>${categoryFilters}</section><section class="study-list">${cards}</section>`, 'study-room');
}
